In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats

from IPython.display import display

In [2]:
# 辅助函数


def E(x, p):
    """Expected value of a discrete random variable."""
    return np.sum(x * p)

In [3]:
def f_S(N, g, f, m, k, b):
    """
    S_k = {
        (m - k) * g - f                  if k >= m - N
        (N * g - f) - (m - k - N) * b    if k <  m - N
    }
    """
    return np.where(k >= m - N, (m - k) * g - f, (N * g - f) - (m - k - N) * b)


def f_P(m, q, distribution):
    """B(m, q) or Poisson(m * q)"""
    k = np.arange(m + 1)
    if distribution == "poisson":
        rv = stats.poisson(m * q)
    elif distribution == "binom":
        rv = stats.binom(m, q)
    else:
        raise ValueError("Invalid distribution")
    return rv.pmf(k)  # type: ignore

In [4]:
def f_0(N, g, f, m_s, b, q, distribution):
    df = pd.DataFrame(columns=["E(S)/f", "P(n>=1)", "P(n>=5)"])
    df.index.name = "m"

    for m in m_s:
        k = np.arange(m + 1)
        n = np.clip(m - k - N, 0, None)
        p = f_P(m, q, distribution=distribution)
        S = f_S(N, g, f, m, k, b)
        E_S = E(S, p)
        E_S_div_f = E_S / f
        P_n_ge_1 = np.sum(p[n >= 1])
        P_n_ge_5 = np.sum(p[n >= 5])

        df.loc[m] = [E_S_div_f, P_n_ge_1, P_n_ge_5]

    return df


N = 300
g = 1
f = 0.6 * N * g
b = 0.2


for q, m_s in [
    (0.05, range(300, 327)),
    (0.1, range(300, 346)),
]:
    df = f_0(N, g, f, m_s, b, q, distribution="binom")
    print(f"q = {q:.2f}")
    display(df)

q = 0.05

       E(S)/f       P(n>=1)       P(n>=5)
m
300  0.583333  0.000000e+00  0.000000e+00
301  0.588611  1.971538e-07  0.000000e+00
302  0.593889  3.164319e-06  0.000000e+00
303  0.599166  2.556641e-05  0.000000e+00
304  0.604443  1.386970e-04  0.000000e+00
305  0.609717  5.685932e-04  1.605830e-07
306  0.614983  1.879777e-03  2.609474e-06
307  0.620226  5.223294e-03  2.134349e-05
308  0.625422  1.255515e-02  1.171992e-04
309  0.630526  2.666898e-02  4.862437e-04
310  0.635474  5.089771e-02  1.626591e-03
311  0.640179  8.845224e-02  4.572489e-03
312  0.644542  1.415407e-01  1.111659e-02
313  0.648464  2.105557e-01  2.387759e-02
314  0.651854  2.936391e-01  4.606755e-02
315  0.654651  3.868113e-01  8.090578e-02
316  0.656827  4.846420e-01  1.307878e-01
317  0.658391  5.812499e-01  1.964658e-01
318  0.659387  6.713225e-01  2.765424e-01
319  0.659883  7.508866e-01  3.674866e-01
320  0.659960  8.176786e-01  4.641905e-01
321  0.659703  8.711122e-01  5.608945e-01
322  0.659191  9.119508e-01  6.521944e-01
323  0.658494  9.418372e-01  7.338571e-01
324  0.657667  9.628226e-01  8.032704e-01
325  0.656752  9.769878e-01  8.594952e-01
326  0.655781  9.861952e-01  9.030024e-01

q = 0.10

       E(S)/f       P(n>=1)       P(n>=5)
m
300  0.500000  0.000000e+00  0.000000e+00
301  0.505000  1.686535e-14  0.000000e+00
302  0.510000  5.245124e-13  0.000000e+00
303  0.515000  8.189982e-12  0.000000e+00
304  0.520000  8.561123e-11  0.000000e+00
305  0.525000  6.740127e-10  1.106536e-14
306  0.530000  4.263262e-09  3.485587e-13
307  0.535000  2.256843e-08  5.512207e-12
308  0.540000  1.028497e-07  5.835354e-11
309  0.545000  4.119325e-07  4.652318e-10
310  0.550000  1.473117e-06  2.979740e-09
311  0.555000  4.762788e-06  1.597136e-08
312  0.560000  1.406359e-05  7.369129e-08
313  0.565000  3.824566e-05  2.987990e-07
314  0.569999  9.646865e-05  1.081674e-06
315  0.574998  2.270545e-04  3.539900e-06
316  0.579994  5.012848e-04  1.057937e-05
317  0.584988  1.042890e-03  2.911663e-05
318  0.589975  2.052823e-03  7.431902e-05
319  0.594951  3.837040e-03  1.769930e-04
320  0.599908  6.832645e-03  3.953464e-04
321  0.604835  1.162561e-02  8.320533e-04
322  0.609716  1.895201e-02  1.656658e-03
323  0.614531  2.967518e-02  3.131786e-03
324  0.619252  4.473426e-02  5.639502e-03
325  0.623848  6.506400e-02  9.702002e-03
326  0.628282  9.149267e-02  1.598920e-02
327  0.632512  1.246302e-01  2.530570e-02
328  0.636497  1.647633e-01  3.855131e-02
329  0.640195  2.117765e-01  5.665366e-02
330  0.643568  2.651121e-01  8.047635e-02
331  0.646587  3.237813e-01  1.107128e-01
332  0.649226  3.864248e-01  1.477805e-01
333  0.651474  4.514174e-01  1.917322e-01
334  0.653329  5.170010e-01  2.422009e-01
335  0.654797  5.814271e-01  2.983894e-01
336  0.655898  6.430921e-01  3.591091e-01
337  0.656655  7.006462e-01  4.228649e-01
338  0.657102  7.530670e-01  4.879731e-01
339  0.657273  7.996939e-01  5.526983e-01
340  0.657204  8.402235e-01  6.153892e-01
341  0.656933  8.746737e-01  6.745973e-01
342  0.656494  9.033261e-01  7.291648e-01
343  0.655919  9.266574e-01  7.782756e-01
344  0.655235  9.452681e-01  8.214678e-01
345  0.654466  9.598183e-01  8.586132e-01

In [5]:
def f_1(N, g, f, b_s, q, distribution):
    df = pd.DataFrame(columns=["使E(S)/f最大的预订水平", "E(S)/f", "P(n>=5)"])
    df.index.name = "b/g"

    for b in b_s:
        m_s = range(N, N + 100)
        result = f_0(N, g, f, m_s, b, q, distribution=distribution)
        m_best = result["E(S)/f"].idxmax()
        E_S_div_f = result.loc[m_best, "E(S)/f"]
        P_n_ge_5 = result.loc[m_best, "P(n>=5)"]
        df.loc[b/g] = [m_best, E_S_div_f, P_n_ge_5]

    df = df.convert_dtypes()
    return df


N = 300
g = 1  # 假设票价为 1
f = 0.6 * N * g

b_s = [0.1, 0.2, 0.3, 0.4, 0.5]
for q in [0.05, 0.10, 0.15]:
    df = f_1(N, g, f, b_s, q, distribution="binom")
    print(f"q = {q:.2f}")
    display(df)

q = 0.05

     使E(S)/f最大的预订水平    E(S)/f   P(n>=5)
b/g
0.1             321  0.662575  0.560894
0.2             320   0.65996  0.464191
0.3             319  0.657905  0.367487
0.4             318  0.656229  0.276542
0.5             317  0.654725  0.196466

q = 0.10

     使E(S)/f最大的预订水平    E(S)/f   P(n>=5)
b/g
0.1             342  0.660953  0.729165
0.2             339  0.657273  0.552698
0.3             338   0.65436  0.487973
0.4             337  0.651931  0.422865
0.5             336  0.649872  0.359109

q = 0.15

     使E(S)/f最大的预订水平    E(S)/f   P(n>=5)
b/g
0.1             364  0.659712  0.766555
0.2             361   0.65519  0.641107
0.3             359  0.651633  0.545045
0.4             357  0.648673   0.44487
0.5             356  0.646128  0.395158

In [6]:
N = 300
g = 1
f = 0.6 * N * g
b = 0.2


q = 0.05
m_s = range(300, 327)

df = f_0(N, g, f, m_s, b, q, distribution="poisson")
print(f"q = {q:.2f}")
display(df)

q = 0.1
m_s = range(300, 346)

df = f_0(N, g, f, m_s, b, q, distribution="poisson")
print(f"q = {q:.2f}")
display(df)

q = 0.05

       E(S)/f       P(n>=1)       P(n>=5)
m
300  0.583333  0.000000e+00  0.000000e+00
301  0.588611  2.909833e-07  0.000000e+00
302  0.593889  4.456349e-06  0.000000e+00
303  0.599166  3.446796e-05  0.000000e+00
304  0.604443  1.795792e-04  0.000000e+00
305  0.609716  7.092749e-04  2.382370e-07
306  0.614979  2.266246e-03  3.693874e-06
307  0.620217  6.104892e-03  2.892057e-05
308  0.625401  1.426958e-02  1.524956e-04
309  0.630487  2.956307e-02  6.094554e-04
310  0.635406  5.519046e-02  1.970014e-03
311  0.640075  9.408736e-02  5.367546e-03
312  0.644397  1.480993e-01  1.268632e-02
313  0.648275  2.172855e-01  2.656928e-02
314  0.651627  2.996079e-01  5.012642e-02
315  0.654396  3.911350e-01  8.632906e-02
316  0.656559  4.867051e-01  1.372255e-01
317  0.658126  5.808415e-01  2.032274e-01
318  0.659139  6.686516e-01  2.827259e-01
319  0.659662  7.464864e-01  3.721926e-01
320  0.659773  8.122485e-01  4.667449e-01
321  0.659552  8.653546e-01  5.610017e-01
322  0.659075  9.064462e-01  6.499773e-01
323  0.658408  9.369796e-01  7.297842e-01
324  0.657605  9.588118e-01  7.980103e-01
325  0.656710  9.738616e-01  8.537539e-01
326  0.655753  9.838804e-01  8.973902e-01

q = 0.10

       E(S)/f       P(n>=1)       P(n>=5)
m
300  0.500000  0.000000e+00  0.000000e+00
301  0.505000  8.467127e-14  0.000000e+00
302  0.510000  2.390349e-12  0.000000e+00
303  0.515000  3.399217e-11  0.000000e+00
304  0.520000  3.246630e-10  0.000000e+00
305  0.525000  2.343052e-09  5.675685e-14
306  0.530000  1.362897e-08  1.622841e-12
307  0.535000  6.656027e-08  2.337114e-11
308  0.540000  2.807272e-07  2.260339e-10
309  0.545000  1.043856e-06  1.651640e-09
310  0.550000  3.476475e-06  9.726167e-09
311  0.555000  1.050013e-05  4.808294e-08
312  0.560000  2.905326e-05  2.052622e-07
313  0.564999  7.426239e-05  7.724390e-07
314  0.569998  1.765926e-04  2.603225e-06
315  0.574996  3.930210e-04  7.955454e-06
316  0.579990  8.229200e-04  2.226947e-05
317  0.584980  1.628451e-03  5.758042e-05
318  0.589961  3.057832e-03  1.384885e-04
319  0.594926  5.468055e-03  3.116989e-04
320  0.599868  9.341880e-03  6.599276e-04
321  0.604772  1.529286e-02  1.320294e-03
322  0.609621  2.405231e-02  2.506128e-03
323  0.614394  3.643400e-02  4.529490e-03
324  0.619063  5.327561e-02  7.820008e-03
325  0.623595  7.536061e-02  1.293434e-02
326  0.627956  1.033288e-01  2.055027e-02
327  0.632107  1.375873e-01  3.144058e-02
328  0.636009  1.782353e-01  4.642454e-02
329  0.639626  2.250156e-01  6.629889e-02
330  0.642926  2.773014e-01  9.175441e-02
331  0.645881  3.341217e-01  1.232883e-01
332  0.648474  3.942247e-01  1.611249e-01
333  0.650693  4.561691e-01  2.051570e-01
334  0.652539  5.184327e-01  2.549183e-01
335  0.654019  5.795243e-01  3.095932e-01
336  0.655149  6.380851e-01  3.680623e-01
337  0.655952  6.929705e-01  4.289809e-01
338  0.656457  7.433035e-01  4.908782e-01
339  0.656694  7.885000e-01  5.522658e-01
340  0.656696  8.282650e-01  6.117416e-01
341  0.656496  8.625667e-01  6.680789e-01
342  0.656126  8.915944e-01  7.202912e-01
343  0.655615  9.157066e-01  7.676692e-01
344  0.654988  9.353777e-01  8.097901e-01
345  0.654270  9.511468e-01  8.465025e-01

In [7]:
def f_S_多票价(N, g, f, m, k, b, j, r):
    """
    S_k = {
        j * r * g + (m - j - k) * g - f                  if k >= m - N
        j * r * g + (N - j) * g - f - (m - k - N) * b    if k <  m - N
    }
    """
    return np.where(k >= m - N,
                    j * r * g + (m - j - k) * g - f,
                    j * r * g + (N - j) * g - f - (m - k - N) * b)

In [8]:
def f_2(N, g, f, m_s, b, q, j, r, distribution):
    df = pd.DataFrame(columns=["E(S)/f", "P(n>=1)", "P(n>=5)"])
    df.index.name = "m"

    for m in m_s:
        k = np.arange(m - j + 1)
        n = np.clip(m - k - N, 0, None)
        p = f_P(m - j, q, distribution=distribution)
        S = f_S_多票价(N, g, f, m, k, b, j, r)
        E_S = E(S, p)
        E_S_div_f = E_S / f
        # print(S, p, E_S, E_S_div_f, sep="\n\n")
        P_n_ge_1 = np.sum(p[n >= 1])
        P_n_ge_5 = np.sum(p[n >= 5])

        df.loc[m] = [E_S_div_f, P_n_ge_1, P_n_ge_5]

    return df


N = 300
g = 1
r = 0.75
b = 0.2
q = 0.05
m_s = range(300, 327)

df_dict = {}
for j in [0, 50, 100, 150]:
    f = 0.6 * (j * r * g + (N - j) * g)
    df = f_2(N, g, f, m_s, b, q, j, r, distribution="binom")
    df_dict[j] = df
    print(f"j = {j}")
    display(df)

j = 0

       E(S)/f       P(n>=1)       P(n>=5)
m
300  0.583333  0.000000e+00  0.000000e+00
301  0.588611  1.971538e-07  0.000000e+00
302  0.593889  3.164319e-06  0.000000e+00
303  0.599166  2.556641e-05  0.000000e+00
304  0.604443  1.386970e-04  0.000000e+00
305  0.609717  5.685932e-04  1.605830e-07
306  0.614983  1.879777e-03  2.609474e-06
307  0.620226  5.223294e-03  2.134349e-05
308  0.625422  1.255515e-02  1.171992e-04
309  0.630526  2.666898e-02  4.862437e-04
310  0.635474  5.089771e-02  1.626591e-03
311  0.640179  8.845224e-02  4.572489e-03
312  0.644542  1.415407e-01  1.111659e-02
313  0.648464  2.105557e-01  2.387759e-02
314  0.651854  2.936391e-01  4.606755e-02
315  0.654651  3.868113e-01  8.090578e-02
316  0.656827  4.846420e-01  1.307878e-01
317  0.658391  5.812499e-01  1.964658e-01
318  0.659387  6.713225e-01  2.765424e-01
319  0.659883  7.508866e-01  3.674866e-01
320  0.659960  8.176786e-01  4.641905e-01
321  0.659703  8.711122e-01  5.608945e-01
322  0.659191  9.119508e-01  6.521944e-01
323  0.658494  9.418372e-01  7.338571e-01
324  0.657667  9.628226e-01  8.032704e-01
325  0.656752  9.769878e-01  8.594952e-01
326  0.655781  9.861952e-01  9.030024e-01

j = 50

       E(S)/f   P(n>=1)   P(n>=5)
m
300  0.594203  0.000000  0.000000
301  0.599710  0.000003  0.000000
302  0.605217  0.000035  0.000000
303  0.610723  0.000237  0.000000
304  0.616222  0.001092  0.000000
305  0.621704  0.003804  0.000002
306  0.627138  0.010720  0.000029
307  0.632471  0.025474  0.000199
308  0.637622  0.052559  0.000928
309  0.642478  0.096233  0.003281
310  0.646912  0.159076  0.009374
311  0.650800  0.240771  0.022575
312  0.654042  0.337691  0.047186
313  0.656581  0.443496  0.087486
314  0.658413  0.550521  0.146369
315  0.659580  0.651431  0.224094
316  0.660162  0.740568  0.317718
317  0.660260  0.814663  0.421485
318  0.659978  0.872849  0.528045
319  0.659416  0.916166  0.630039
320  0.658655  0.946829  0.721493
321  0.657761  0.967527  0.798657
322  0.656781  0.980882  0.860162
323  0.655749  0.989138  0.906632
324  0.654685  0.994038  0.940017
325  0.653603  0.996835  0.962886
326  0.652512  0.998373  0.977859

j = 100

       E(S)/f   P(n>=1)   P(n>=5)
m
300  0.606061  0.000000  0.000000
301  0.611818  0.000033  0.000000
302  0.617573  0.000368  0.000000
303  0.623316  0.002058  0.000000
304  0.629017  0.007776  0.000000
305  0.634615  0.022357  0.000027
306  0.640001  0.052248  0.000305
307  0.645024  0.103561  0.001737
308  0.649515  0.179431  0.006676
309  0.653315  0.278062  0.019519
310  0.656319  0.392583  0.046361
311  0.658489  0.512830  0.093334
312  0.659865  0.628159  0.164129
313  0.660542  0.730032  0.257932
314  0.660648  0.813489  0.368932
315  0.660322  0.877275  0.487702
316  0.659686  0.922988  0.603774
317  0.658842  0.953844  0.708237
318  0.657866  0.973538  0.795425
319  0.656810  0.985463  0.863306
320  0.655709  0.992336  0.912860
321  0.654583  0.996116  0.946928
322  0.653444  0.998105  0.969072
323  0.652298  0.999109  0.982727
324  0.651150  0.999595  0.990741
325  0.649999  0.999822  0.995229
326  0.648848  0.999925  0.997633

j = 150

       E(S)/f   P(n>=1)   P(n>=5)
m
300  0.619048  0.000000  0.000000
301  0.625076  0.000433  0.000000
302  0.631080  0.003700  0.000000
303  0.636990  0.016117  0.000000
304  0.642664  0.047778  0.000000
305  0.647886  0.108727  0.000352
306  0.652411  0.203198  0.003084
307  0.656036  0.326010  0.013739
308  0.658659  0.463735  0.041617
309  0.660298  0.599738  0.096678
310  0.661073  0.719875  0.184224
311  0.661162  0.815984  0.300953
312  0.660752  0.886318  0.435190
313  0.660006  0.933794  0.571106
314  0.659052  0.963557  0.694185
315  0.657977  0.980990  0.795110
316  0.656835  0.990578  0.870804
317  0.655659  0.995552  0.923158
318  0.654466  0.997995  0.956786
319  0.653266  0.999135  0.976963
320  0.652062  0.999642  0.988329
321  0.650857  0.999858  0.994368
322  0.649651  0.999946  0.997405
323  0.648444  0.999980  0.998855
324  0.647238  0.999993  0.999516
325  0.646032  0.999998  0.999803
326  0.644825  0.999999  0.999923

In [9]:
df = pd.DataFrame(columns=["使E(S)/f最大的预订水平", "E(S)/f", "P(n>=5)"])
df.index.name = "j"
for j, result in df_dict.items():
    m_best = result["E(S)/f"].idxmax()
    E_S_div_f = result.loc[m_best, "E(S)/f"]
    P_n_ge_5 = result.loc[m_best, "P(n>=5)"]
    df.loc[j] = [m_best, E_S_div_f, P_n_ge_5]

df = df.convert_dtypes()
df

     使E(S)/f最大的预订水平    E(S)/f   P(n>=5)
j
0               320   0.65996  0.464191
50              317   0.66026  0.421485
100             314  0.660648  0.368932
150             311  0.661162  0.300953

In [10]:
N = 300
g = 1
r = 0.75
b = 0.2
q = 0.05
m_s = range(300, 327)

df_dict = {}
for j in [0, 50, 100, 150]:
    f = 0.6 * (j * r * g + (N - j) * g)
    df = f_2(N, g, f, m_s, b, q, j, r, distribution="poisson")
    df_dict[j] = df
    print(f"j = {j}")
    display(df)

df = pd.DataFrame(columns=["使E(S)/f最大的预订水平", "E(S)/f", "P(n>=5)"])
df.index.name = "j"
for j, result in df_dict.items():
    m_best = result["E(S)/f"].idxmax()
    E_S_div_f = result.loc[m_best, "E(S)/f"]
    P_n_ge_5 = result.loc[m_best, "P(n>=5)"]
    df.loc[j] = [m_best, E_S_div_f, P_n_ge_5]

df = df.convert_dtypes()
display(df)

j = 0

       E(S)/f       P(n>=1)       P(n>=5)
m
300  0.583333  0.000000e+00  0.000000e+00
301  0.588611  2.909833e-07  0.000000e+00
302  0.593889  4.456349e-06  0.000000e+00
303  0.599166  3.446796e-05  0.000000e+00
304  0.604443  1.795792e-04  0.000000e+00
305  0.609716  7.092749e-04  2.382370e-07
306  0.614979  2.266246e-03  3.693874e-06
307  0.620217  6.104892e-03  2.892057e-05
308  0.625401  1.426958e-02  1.524956e-04
309  0.630487  2.956307e-02  6.094554e-04
310  0.635406  5.519046e-02  1.970014e-03
311  0.640075  9.408736e-02  5.367546e-03
312  0.644397  1.480993e-01  1.268632e-02
313  0.648275  2.172855e-01  2.656928e-02
314  0.651627  2.996079e-01  5.012642e-02
315  0.654396  3.911350e-01  8.632906e-02
316  0.656559  4.867051e-01  1.372255e-01
317  0.658126  5.808415e-01  2.032274e-01
318  0.659139  6.686516e-01  2.827259e-01
319  0.659662  7.464864e-01  3.721926e-01
320  0.659773  8.122485e-01  4.667449e-01
321  0.659552  8.653546e-01  5.610017e-01
322  0.659075  9.064462e-01  6.499773e-01
323  0.658408  9.369796e-01  7.297842e-01
324  0.657605  9.588118e-01  7.980103e-01
325  0.656710  9.738616e-01  8.537539e-01
326  0.655753  9.838804e-01  8.973902e-01

j = 50

       E(S)/f   P(n>=1)   P(n>=5)
m
300  0.594203  0.000000  0.000000
301  0.599710  0.000004  0.000000
302  0.605217  0.000046  0.000000
303  0.610722  0.000300  0.000000
304  0.616220  0.001330  0.000000
305  0.621697  0.004474  0.000003
306  0.627121  0.012222  0.000038
307  0.632436  0.028254  0.000253
308  0.637557  0.056908  0.001136
309  0.642373  0.102066  0.003877
310  0.646762  0.165812  0.010734
311  0.650605  0.247413  0.025139
312  0.653811  0.343095  0.051278
313  0.656329  0.446713  0.093094
314  0.658158  0.551068  0.153004
315  0.659338  0.649385  0.230835
316  0.659947  0.736478  0.323440
317  0.660079  0.809340  0.425193
318  0.659835  0.867129  0.529157
319  0.659308  0.910733  0.628517
320  0.658578  0.942128  0.717793
321  0.657708  0.963756  0.793539
322  0.656746  0.978049  0.854463
323  0.655727  0.987128  0.901075
324  0.654672  0.992684  0.935100
325  0.653596  0.995965  0.958864
326  0.652508  0.997839  0.974782

j = 100

       E(S)/f   P(n>=1)   P(n>=5)
m
300  0.606061  0.000000  0.000000
301  0.611818  0.000043  0.000000
302  0.617572  0.000456  0.000000
303  0.623312  0.002449  0.000000
304  0.629006  0.008924  0.000000
305  0.634586  0.024863  0.000035
306  0.639941  0.056554  0.000380
307  0.644922  0.109571  0.002077
308  0.649364  0.186327  0.007698
309  0.653119  0.284488  0.021802
310  0.656091  0.397133  0.050380
311  0.658250  0.514565  0.099097
312  0.659634  0.626900  0.170950
313  0.660336  0.726317  0.264549
314  0.660478  0.808282  0.373934
315  0.660190  0.871605  0.490049
316  0.659590  0.917679  0.603128
317  0.658776  0.949392  0.704994
318  0.657823  0.970119  0.790465
319  0.656784  0.983027  0.857657
320  0.655694  0.990711  0.907396
321  0.654575  0.995093  0.942221
322  0.653439  0.997495  0.965371
323  0.652296  0.998762  0.980032
324  0.651148  0.999407  0.988905
325  0.649999  0.999724  0.994050
326  0.648848  0.999875  0.996916

j = 150

       E(S)/f   P(n>=1)   P(n>=5)
m
300  0.619048  0.000000  0.000000
301  0.625075  0.000526  0.000000
302  0.631075  0.004304  0.000000
303  0.636970  0.018047  0.000000
304  0.642614  0.051819  0.000000
305  0.647790  0.114868  0.000431
306  0.652263  0.210251  0.003606
307  0.655844  0.332036  0.015458
308  0.658443  0.467004  0.045334
309  0.660083  0.599526  0.102531
310  0.660882  0.716624  0.191236
311  0.661008  0.810892  0.307306
312  0.660637  0.880722  0.439092
313  0.659928  0.928711  0.571619
314  0.659002  0.959519  0.691519
315  0.657947  0.978100  0.790320
316  0.656818  0.988684  0.865213
317  0.655650  0.994401  0.917866
318  0.654462  0.997341  0.952436
319  0.653264  0.998785  0.973755
320  0.652061  0.999465  0.986167
321  0.650856  0.999773  0.993018
322  0.649650  0.999906  0.996618
323  0.648444  0.999963  0.998424
324  0.647238  0.999986  0.999293
325  0.646032  0.999995  0.999693
326  0.644825  0.999998  0.999871

     使E(S)/f最大的预订水平    E(S)/f   P(n>=5)
j
0               320  0.659773  0.466745
50              317  0.660079  0.425193
100             314  0.660478  0.373934
150             311  0.661008  0.307306

In [11]:
def f_S_多票价2(N, g, f, m, k1, k2, b, j, r):
    """
    S_k = {
        j * r * g + (m - j - k2) * g - f                            if k1 + k2 >= m - N
        j * r * g + (N - j + k1) * g - f - (m - k1 - k2 - N) * b    if k1 + k2 <  m - N
    }
    """
    return np.where(k1 + k2 >= m - N,
                    j * r * g + (m - j - k2) * g - f,
                    j * r * g + (N - j + k1) * g - f - (m - k1 - k2 - N) * b)


def f_3(N, g, f, m_s, b, q1, q2, j, r, distribution):
    df = pd.DataFrame(columns=["E(S)/f", "P(n>=1)", "P(n>=5)"])
    df.index.name = "m"

    for m in m_s:
        k1 = np.arange(j + 1)
        P1 = f_P(j, q1, distribution=distribution)
        k2 = np.arange(m - j + 1)[:, np.newaxis]
        P2 = f_P(m - j, q2, distribution=distribution)[:, np.newaxis]
        k = k1 + k2
        P = P1 * P2
        S = f_S_多票价2(N, g, f, m, k1, k2, b, j, r)
        E_S = E(S, P)
        E_S_div_f = E_S / f
        n = np.clip(m - k - N, 0, None)
        P_n_ge_1 = np.sum(P[n >= 1])
        P_n_ge_5 = np.sum(P[n >= 5])

        df.loc[m] = [E_S_div_f, P_n_ge_1, P_n_ge_5]

    return df


N = 300
g = 1
r = 0.75
b = 0.2
q1 = 0.02
q2 = 0.05
m_s = range(300, 327)

df_dict = {}
for j in [0, 50, 100, 150]:
    f = 0.6 * (j * r * g + (N - j) * g)
    df = f_3(N, g, f, m_s, b, q1, q2, j, r, distribution="binom")
    df_dict[j] = df
    print(f"j = {j}")
    display(df)

j = 0

       E(S)/f       P(n>=1)       P(n>=5)
m
300  0.583333  0.000000e+00  0.000000e+00
301  0.588611  1.971538e-07  0.000000e+00
302  0.593889  3.164319e-06  0.000000e+00
303  0.599166  2.556641e-05  0.000000e+00
304  0.604443  1.386970e-04  0.000000e+00
305  0.609717  5.685932e-04  1.605830e-07
306  0.614983  1.879777e-03  2.609474e-06
307  0.620226  5.223294e-03  2.134349e-05
308  0.625422  1.255515e-02  1.171992e-04
309  0.630526  2.666898e-02  4.862437e-04
310  0.635474  5.089771e-02  1.626591e-03
311  0.640179  8.845224e-02  4.572489e-03
312  0.644542  1.415407e-01  1.111659e-02
313  0.648464  2.105557e-01  2.387759e-02
314  0.651854  2.936391e-01  4.606755e-02
315  0.654651  3.868113e-01  8.090578e-02
316  0.656827  4.846420e-01  1.307878e-01
317  0.658391  5.812499e-01  1.964658e-01
318  0.659387  6.713225e-01  2.765424e-01
319  0.659883  7.508866e-01  3.674866e-01
320  0.659960  8.176786e-01  4.641905e-01
321  0.659703  8.711122e-01  5.608945e-01
322  0.659191  9.119508e-01  6.521944e-01
323  0.658494  9.418372e-01  7.338571e-01
324  0.657667  9.628226e-01  8.032704e-01
325  0.656752  9.769878e-01  8.594952e-01
326  0.655781  9.861952e-01  9.030024e-01

j = 50

       E(S)/f       P(n>=1)       P(n>=5)
m
300  0.594203  0.000000e+00  0.000000e+00
301  0.599710  9.331011e-07  0.000000e+00
302  0.605217  1.354806e-05  0.000000e+00
303  0.610724  9.915052e-05  0.000000e+00
304  0.616228  4.878933e-04  0.000000e+00
305  0.621723  1.817000e-03  7.600167e-07
306  0.627192  5.466229e-03  1.118698e-05
307  0.632605  1.384747e-02  8.298471e-05
308  0.637906  3.040935e-02  4.138216e-04
309  0.643012  5.915374e-02  1.561483e-03
310  0.647819  1.036652e-01  4.758409e-03
311  0.652208  1.659319e-01  1.220732e-02
312  0.656065  2.454127e-01  2.713947e-02
313  0.659301  3.387572e-01  5.342825e-02
314  0.661863  4.403252e-01  9.472062e-02
315  0.663744  5.433252e-01  1.533088e-01
316  0.664980  6.411718e-01  2.291576e-01
317  0.665642  7.286319e-01  3.194988e-01
318  0.665820  8.024776e-01  4.191861e-01
319  0.665613  8.615778e-01  5.217002e-01
320  0.665113  9.065495e-01  6.204490e-01
321  0.664402  9.391763e-01  7.099472e-01
322  0.663545  9.618007e-01  7.865639e-01
323  0.662592  9.768295e-01  8.487310e-01
324  0.661577  9.864127e-01  8.966890e-01
325  0.660524  9.922897e-01  9.319606e-01
326  0.659450  9.957619e-01  9.567539e-01

j = 100

       E(S)/f   P(n>=1)   P(n>=5)
m
300  0.606061  0.000000  0.000000
301  0.611818  0.000004  0.000000
302  0.617575  0.000057  0.000000
303  0.623330  0.000376  0.000000
304  0.629076  0.001662  0.000000
305  0.634793  0.005569  0.000004
306  0.640443  0.015108  0.000047
307  0.645955  0.034605  0.000316
308  0.651224  0.068914  0.001416
309  0.656119  0.121978  0.004814
310  0.660501  0.195253  0.013247
311  0.664244  0.286718  0.030764
312  0.667263  0.390967  0.062088
313  0.669524  0.500361  0.111315
314  0.671050  0.606783  0.180381
315  0.671913  0.703336  0.267971
316  0.672214  0.785446  0.369389
317  0.672067  0.851190  0.477495
318  0.671582  0.900946  0.584320
319  0.670855  0.936660  0.682756
320  0.669963  0.961049  0.767773
321  0.668966  0.976938  0.836902
322  0.667901  0.986838  0.890028
323  0.666798  0.992750  0.928747
324  0.665672  0.996141  0.955593
325  0.664533  0.998013  0.973350
326  0.663388  0.999010  0.984580

j = 150

       E(S)/f   P(n>=1)   P(n>=5)
m
300  0.619048  0.000000  0.000000
301  0.625079  0.000021  0.000000
302  0.631109  0.000239  0.000000
303  0.637130  0.001389  0.000000
304  0.643121  0.005441  0.000000
305  0.649032  0.016212  0.000017
306  0.654770  0.039245  0.000198
307  0.660204  0.080513  0.001171
308  0.665167  0.144235  0.004663
309  0.669495  0.230792  0.014120
310  0.673056  0.335863  0.034720
311  0.675778  0.451264  0.072313
312  0.677661  0.567098  0.131429
313  0.678771  0.674239  0.213200
314  0.679222  0.766194  0.314267
315  0.679147  0.839860  0.427278
316  0.678678  0.895224  0.542752
317  0.677931  0.934433  0.651469
318  0.676999  0.960701  0.746434
319  0.675950  0.977407  0.823855
320  0.674830  0.987522  0.883062
321  0.673670  0.993370  0.925725
322  0.672487  0.996606  0.954804
323  0.671292  0.998324  0.973615
324  0.670091  0.999200  0.985201
325  0.668887  0.999631  0.992014
326  0.667682  0.999835  0.995847

In [12]:
df = pd.DataFrame(columns=["使E(S)/f最大的预订水平", "E(S)/f", "P(n>=5)"])
df.index.name = "j"
for j, result in df_dict.items():
    m_best = result["E(S)/f"].idxmax()
    E_S_div_f = result.loc[m_best, "E(S)/f"]
    P_n_ge_5 = result.loc[m_best, "P(n>=5)"]
    df.loc[j] = [m_best, E_S_div_f, P_n_ge_5]

df = df.convert_dtypes()
df

     使E(S)/f最大的预订水平    E(S)/f   P(n>=5)
j
0               320   0.65996  0.464191
50              318   0.66582  0.419186
100             316  0.672214  0.369389
150             314  0.679222  0.314267